# Use OpenJDK 17 as the base image
FROM openjdk:17-jdk-slim

# Install Maven to build the Spring Boot application
RUN apt-get update && apt-get install -y maven

# Set the working directory inside the container
WORKDIR /app

# Copy the pom.xml and source code into the container
COPY pom.xml /app/
COPY src /app/src/

# Run Maven to build the JAR file
RUN mvn clean package

# Copy the JAR file generated by Maven into the container
COPY target/Jobify-0.0.1-SNAPSHOT.jar /app/jobify.jar

# Command to run the application
ENTRYPOINT ["java", "-jar", "/app/jobify.jar"]
