# Use OpenJDK 17 as the base image
FROM openjdk:17-jdk-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the JAR file generated by Maven into the container
COPY target/Jobify-0.0.1-SNAPSHOT.jar /app/jobify.jar

# Command to run the application
ENTRYPOINT ["java", "-jar", "/app/jobify.jar"]
